FROM golang:1.24.3-bullseye

RUN  apt-get && apt-get install -y  librdkafka-dev && rm -rf var/lib/apt/lists/*

WORKDIR /app

COPY  go.mod go.sum ./

RUN go mod download

COPY micro2/main.go ./

RUN go build -o kafka-microservice-2

ENTRYPOINT ["./kafka-microservice-2"]