#base image with go
FROM golang:1.24.3-bullseye

# Install librdkafka dependencies for confluent-kafka-go
RUN apt-get update && apt-get install -y \
    librdkafka-dev \
    && rm -rf /var/lib/apt/lists/*

#setting the workdir
WORKDIR /app

#copy go.mod go.sum files first for better caching
COPY go.mod go.sum ./

#download dependancies
RUN go mod download

#copy the source code
COPY micro1/main.go ./

#build the go app
RUN go build -o kafka-microservice-1

#run the binary
ENTRYPOINT ["./kafka-microservice-1"]