#first we define the namespace it will run in
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-ns

---
#deployment for both kafka and zookeeper
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: kafka-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image:  confluentinc/cp-zookeeper:7.5.0
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value:  "2000"

---

#zookeeper service
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: kafka-ns
spec:
  selector:
    app:  zookeeper
  ports:
  - protocol: TCP
    port: 2181
    targetPort: 2181

---
#kafka persistent vlumne claims
apiVersion:  v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: kafka-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage:  2Gi

---
#kafka deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace:  kafka-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template: 
    metadata:
      labels:
        app:  kafka
    spec:
      volumes: 
      - name: kafka-storage
        persistentVolumeClaim:
          claimName: kafka-pvc
      containers:
      - name: kafka
        image:  confluentinc/cp-kafka:7.5.0
        ports:
        - containerPort: 9092
        volumeMounts:
        - name: kafka-storage
          mountPath: /var/lib/kafka/data
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-service.kafka.ns.svc.cluster.local:9002
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value:  "1"

---
#kafka service
apiVersion: v1
kind: Service
metadata: 
  name: kafka-service
  namespace: kafka-ns
spec:
  selector:
    app: kafka
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
          